
// Objective-C API for talking to the following Go packages
//
//	github.com/bcl-chain/web3.go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Geth_FRAMEWORK_H__
#define __Geth_FRAMEWORK_H__

#include "Geth.objc.h"
#include "Universe.objc.h"

#endif
